global:
  scrape_interval: 4s

scrape_configs:
  - job_name: prometheus
    metrics_path: "/metrics"
    static_configs:
      - targets: ["host.docker.internal:8000"] # for docker dev or - targets: ["fastapi:8000"]
